.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. bitcoinblue_qt test_bitcoinblue_qt
clean: FORCE
	$(MAKE) -C .. bitcoinblue_qt_clean test_bitcoinblue_qt_clean
check: FORCE
	$(MAKE) -C .. test_bitcoinblue_qt_check
bitcoinblue-qt bitcoinblue-qt.exe: FORCE
	 $(MAKE) -C .. bitcoinblue_qt
